import { StadiumLayoutConfig } from "../layout/types";

export const LAYOUT_SCHEMAS: Record<string, StadiumLayoutConfig> = {
  leftRightBoxes: {
    stands: {
      north: true,
      south: true,
      east: false,
      west: false,
    },
    boxes: {
      placement: "left-right",
      countPerSide: 3,
    },
  },
  topBottomBoxes: {
    dimensions: {
      width: 900,
      height: 760,
      groundRadius: 140,
    },
    stands: {
      north: false,
      south: false,
      east: false,
      west: false,
    },
    boxes: {
      placement: "top-bottom",
      items: [
        { type: "top", row: 1, order: 1, name: "Top R1 O1", capacity: 100, available: 70 },
        { type: "top", row: 1, order: 2, name: "Top R1 O2", capacity: 90, available: 20 },
        { type: "top", row: 1, order: 3, name: "Top R1 O3", capacity: 95, available: 48 },
        { type: "top", row: 1, order: 4, name: "Top R1 O4", capacity: 92, available: 33 },
        { type: "top", row: 2, order: 1, name: "Top R2 O1", capacity: 110, available: 6 },
        { type: "top", row: 2, order: 2, name: "Top R2 O2", capacity: 120, available: 80 },
        { type: "top", row: 2, order: 3, name: "Top R2 O3", capacity: 115, available: 55 },
        { type: "top", row: 2, order: 4, name: "Top R2 O4", capacity: 105, available: 30 },
        { type: "bottom", row: 1, order: 1, name: "Bottom R1 O1", capacity: 95, available: 65 },
        { type: "bottom", row: 1, order: 2, name: "Bottom R1 O2", capacity: 85, available: 10 },
        { type: "bottom", row: 1, order: 3, name: "Bottom R1 O3", capacity: 91, available: 36 },
        { type: "bottom", row: 1, order: 4, name: "Bottom R1 O4", capacity: 97, available: 50 },
        { type: "bottom", row: 2, order: 1, name: "Bottom R2 O1", capacity: 105, available: 40 },
        { type: "bottom", row: 2, order: 2, name: "Bottom R2 O2", capacity: 88, available: 12 },
        { type: "bottom", row: 2, order: 3, name: "Bottom R2 O3", capacity: 99, available: 61 },
        { type: "bottom", row: 2, order: 4, name: "Bottom R2 O4", capacity: 93, available: 5 },
        { type: "left", row: 1, order: 1, name: "Left R1 O1", capacity: 100, available: 55 },
        { type: "left", row: 1, order: 2, name: "Left R1 O2", capacity: 90, available: 30 },
        { type: "left", row: 1, order: 3, name: "Left R1 O3", capacity: 85, available: 18 },
        { type: "left", row: 1, order: 4, name: "Left R1 O4", capacity: 96, available: 42 },
        { type: "left", row: 2, order: 1, name: "Left R2 O1", capacity: 80, available: 0 },
        { type: "left", row: 2, order: 2, name: "Left R2 O2", capacity: 89, available: 27 },
        { type: "left", row: 2, order: 3, name: "Left R2 O3", capacity: 94, available: 65 },
        { type: "left", row: 2, order: 4, name: "Left R2 O4", capacity: 87, available: 20 },
        { type: "right", row: 1, order: 1, name: "Right R1 O1", capacity: 110, available: 72 },
        { type: "right", row: 1, order: 2, name: "Right R1 O2", capacity: 75, available: 6 },
        { type: "right", row: 1, order: 3, name: "Right R1 O3", capacity: 98, available: 49 },
        { type: "right", row: 1, order: 4, name: "Right R1 O4", capacity: 93, available: 35 },
        { type: "right", row: 2, order: 1, name: "Right R2 O1", capacity: 98, available: 25 },
        { type: "right", row: 2, order: 2, name: "Right R2 O2", capacity: 101, available: 73 },
        { type: "right", row: 2, order: 3, name: "Right R2 O3", capacity: 90, available: 4 },
        { type: "right", row: 2, order: 4, name: "Right R2 O4", capacity: 86, available: 15 },
        { type: "top-left", row: 1, order: 1, name: "Top Left R1 O1", capacity: 70, available: 45 },
        { type: "top-left", row: 1, order: 2, name: "Top Left R1 O2", capacity: 70, available: 45 },
        { type: "top-left", row: 2, order: 1, name: "Top Left R2 O1", capacity: 76, available: 50 },
        { type: "top-left", row: 2, order: 2, name: "Top Left R2 O2", capacity: 68, available: 0 },
        { type: "top-right", row: 1, order: 1, name: "Top Right R1 O1", capacity: 72, available: 40 },
        { type: "top-right", row: 1, order: 2, name: "Top Right R1 O2", capacity: 72, available: 40 },
        { type: "top-right", row: 2, order: 1, name: "Top Right R2 O1", capacity: 80, available: 63 },
        { type: "top-right", row: 2, order: 2, name: "Top Right R2 O2", capacity: 75, available: 3 },
        { type: "bottom-left", row: 1, order: 1, name: "Bottom Left R1 O1", capacity: 68, available: 20 },
        { type: "bottom-left", row: 1, order: 2, name: "Bottom Left R1 O2", capacity: 68, available: 0 },
        { type: "bottom-left", row: 2, order: 1, name: "Bottom Left R2 O1", capacity: 73, available: 52 },
        { type: "bottom-left", row: 2, order: 2, name: "Bottom Left R2 O2", capacity: 78, available: 60 },
        { type: "bottom-right", row: 1, order: 1, name: "Bottom Right R1 O1", capacity: 74, available: 58 },
        { type: "bottom-right", row: 1, order: 2, name: "Bottom Right R1 O2", capacity: 74, available: 58 },
        { type: "bottom-right", row: 2, order: 1, name: "Bottom Right R2 O1", capacity: 82, available: 0 },
        { type: "bottom-right", row: 2, order: 2, name: "Bottom Right R2 O2", capacity: 77, available: 39 },
      ],
    },
  },
};
